apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-scanner.fullname" . }}
  namespace: {{ include "cluster-scanner.namespace" . }}
  labels:
    {{- include "cluster-scanner.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not ( include "cluster-scanner.accessKeySecret" . ) }}
  sysdig_access_key: {{ required "please provide a sysdig access key" .Values.global.sysdig.accessKey | b64enc | quote }}
{{- end }}
  js_server_password: {{ .Values.runtimeStatusIntegrator.natsJS.password | default (randAlphaNum 32) | b64enc | quote }}
{{- if and (eq .Values.imageSbomExtractor.cache.type "distributed") ((.Values.imageSbomExtractor.cache.redis).password) }}
  cache_redis_password: {{ .Values.imageSbomExtractor.cache.redis.password | b64enc | quote }}
{{- end }}
{{- if .Values.runtimeStatusIntegrator.natsJS.tls.enabled }}
  {{- if eq (include "cluster-scanner.nats.tls.customTLS" .) "true" }}
  js_tls_key_path: {{ required "please provide a TLS private key path" .Values.runtimeStatusIntegrator.natsJS.tls.key |  quote }}
  js_tls_cert_path: {{ required "please provide a TLS certificate path" .Values.runtimeStatusIntegrator.natsJS.tls.cert | quote }}
  {{- else }}
  {{- include "cluster-scanner.nats.tls.certificate" . }}
  {{- end }}
{{- end }}
{{- if eq (include "sysdig.custom_ca.useValues"  (dict "global" .Values.global.ssl "component" .Values.ssl)) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-scanner.fullname" . }}-ca
  namespace: {{ include "cluster-scanner.namespace" . }}
  labels:
{{ include "cluster-scanner.labels" . | indent 4 }}
data:
  {{ include "sysdig.custom_ca.keyName" (dict "global" .Values.global.ssl "component" .Values.ssl) }}: {{ include "sysdig.custom_ca.cert" (dict "global" .Values.global.ssl "component" .Values.ssl "Files" .Subcharts.common.Files) | b64enc | quote }}
{{- end }}
